question_data = [
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Type 1 diabetes is a result of the liver working improperly.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Gothenburg is the capital of Sweden.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Adolf Hitler was born in Australia. ",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "hard",
        "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The majority of Subaru vehicles are made in China.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The man that shot Alexander Hamilton was named Aaron Burr.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
